# Plugin tasks

- id: ceph-conf-controller
  type: puppet
  groups: [primary-controller, controller]
  required_for: [deploy_end]
  requires: [openstack-cinder, glance, keystone]
  version: 2.0.0
  parameters:
    puppet_manifest: conf.pp
    puppet_modules: /etc/puppet/modules:puppet/modules
    timeout: 3600

- id: ceph-conf-compute
  type: puppet
  groups: [compute]
  required_for: [deploy_end]
  requires: [top-role-compute]
  version: 2.0.0
  parameters:
    puppet_manifest: conf.pp
    puppet_modules: /etc/puppet/modules:puppet/modules
    timeout: 3600

- id: ceph-volumes-controller
  type: puppet
  groups: [primary-controller, controller]
  required_for: [deploy_end, controller_remaining_tasks]
  requires: [ceph-conf-controller]
  version: 2.0.0
  condition: "settings:external-ceph.cinder_ceph.value == true"
  parameters:
    puppet_manifest: volumes-controller.pp
    puppet_modules: /etc/puppet/modules:puppet/modules
    timeout: 3600

- id: ceph-volumes-and-ephemeral-compute
  type: puppet
  groups: [compute]
  required_for: [deploy_end]
  requires: [top-role-compute, ceph-conf-compute]
  version: 2.0.0
  condition: "settings:external-ceph.cinder_ceph.value == true"
  parameters:
    puppet_manifest: volumes-and-ephemeral-compute.pp
    puppet_modules: /etc/puppet/modules:puppet/modules
    timeout: 3600

- id: ceph-images-controller
  type: puppet
  groups: [primary-controller, controller]
  required_for: [deploy_end, controller_remaining_tasks]
  requires: [ceph-conf-controller]
  version: 2.0.0
  condition: "settings:external-ceph.glance_ceph.value == true"
  parameters:
    puppet_manifest: images.pp
    puppet_modules: /etc/puppet/modules:puppet/modules
    timeout: 3600

- id: ceph-radosgw-controller
  type: puppet
  groups: [primary-controller, controller]
  required_for: [deploy_end, controller_remaining_tasks]
  requires: [ceph-conf-controller]
  version: 2.0.0
  condition: "settings:external-ceph.deploy_radosgw.value == true"
  parameters:
    puppet_manifest: radosgw.pp
    puppet_modules: /etc/puppet/modules:puppet/modules
    timeout: 3600

- id: ceph-radosgw-controller
  type: puppet
  groups: [primary-controller, controller]
  required_for: [deploy_end, controller_remaining_tasks]
  requires: [ceph-conf-controller, ceph-radosgw-controller]
  version: 2.0.0
  condition: "settings:external-ceph.deploy_swift.value == false"
  parameters:
    puppet_manifest: radosgw-keystone.pp
    puppet_modules: /etc/puppet/modules:puppet/modules
    timeout: 3600


# Re-define swift tasks with plugin conditions
- id: swift
  type: puppet
  version: 2.0.0
  groups: [controller]
  required_for: [deploy_end, controller_remaining_tasks]
  requires: [openstack-controller]
  cross-depends:
    - name: primary-swift
  condition: "settings:external-ceph.deploy_swift.value == true"
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/swift/swift.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
  test_pre:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/swift/swift_pre.rb
  test_post:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/swift/swift_post.rbo

- id: primary-swift
  type: puppet
  version: 2.0.0
  groups: [primary-controller]
  required_for: [deploy_end, controller_remaining_tasks]
  requires: [openstack-controller]
  cross-depends:
    - name: /(primary-)?rabbitmq/
    - name: swift-keystone
    - name: memcached
  condition: "settings:external-ceph.deploy_swift.value == true"
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/swift/swift.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
  test_pre:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/swift/swift_pre.rb
  test_post:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/swift/swift_post.rb

- id: swift-rebalance-cron
  type: puppet
  version: 2.0.0
  groups: [primary-controller, controller]
  required_for: [deploy_end]
  requires: [primary-swift, swift]
  cross-depends:
    - name: /(primary-)?swift/
      role: self
  condition: "settings:external-ceph.deploy_swift.value == true"
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/swift/rebalance_cronjob.pp
    puppet_modules: /etc/puppet/modules
    timeout: 300
  test_pre:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/swift/swift_post.rb
  test_post:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/swift/rebalance_cronjob_post.rb

- id: swift-keystone
  type: puppet
  version: 2.0.0
  groups: [primary-controller]
  required_for: [primary-swift]
  cross-depends:
    - name: keystone
  requires: [primary-keystone, keystone]
  condition: "settings:external-ceph.deploy_swift.value == true"
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/swift/keystone.pp
    puppet_modules: /etc/puppet/modules
    timeout: 1800

