attributes:
  metadata:
    group: 'storage'
  ceph_fsid:
    value: 'aa6e4daa-9be1-4165-bf02-7d79e7779bf6'
    label: 'Ceph Cluster FSID'
    description: 'Should be set to the value of "fsid" setting in /etc/ceph/ceph.conf on the mon node of Ceph cluster'
    weight: 1
    type: 'text'
  ceph_mons:
    value: '192.168.0.3 192.168.0.5 192.168.0.4'
    label: 'Ceph Mons IP Addresses'
    description: 'Should be set to the value of "mon_host" setting in /etc/ceph/ceph.conf on the mon node of Ceph cluster'
    weight: 2
    type: 'text'
  external_radosgw:
    value: True
    label: 'Use RadosGW for Object Storage'
    description: "If checked, OpenStack will use external RadosGW for object storage. Please note that external RadosGW must be configured to use this cluster's Keystone for authentication. See README for details"
    weight: 3
    type: 'checkbox'
  radosgw_endpoint_public:
    value: ''
    label: 'External RadosGW Public Endpoint'
    description: ''
    weight: 5
    type: 'text'
    restrictions:
      - condition: "settings:external-ceph.external_radosgw.value == false"
        message: "External RadosGW is disabled"
  radosgw_endpoint_internal:
    value: ''
    label: 'External RadosGW Internal Endpoint'
    description: ''
    weight: 6
    type: 'text'
    restrictions:
      - condition: "settings:external-ceph.external_radosgw.value == false"
        message: "External RadosGW is disabled"
  radosgw_endpoint_admin:
    value: ''
    label: 'External RadosGW Admin Endpoint'
    description: ''
    weight: 7
    type: 'text'
    restrictions:
      - condition: "settings:external-ceph.external_radosgw.value == false"
        message: "External RadosGW is disabled"
  glance_ceph:
    value: True
    label: 'Use Ceph as a backend for Glance (Images)'
    description: ''
    weight: 9
    type: 'checkbox'
  cinder_ceph:
    value: True
    label: 'Use Ceph as a backend for Cinder (Volumes)'
    weight: 10
    type: 'checkbox'
  nova_ceph:
    value: True
    label: 'Use Ceph as a backend for Nova Ephemeral Drives'
    description: ''
    weight: 15
    type: 'checkbox'
    restrictions:
      - condition: "settings:external-ceph.cinder_ceph.value == false"
        message: "Ceph Backend for Cinder must be enabled in order to use Ceph for Ephemeral Drives"
  glance_user:
    value: 'glance'
    label: 'Ceph User for Glance'
    description: 'Username that Glance is going to use to access Ceph'
    weight: 20
    type: 'text'
    restrictions:
      - condition: "settings:external-ceph.glance_ceph.value == false"
        message: "External Ceph for Glance images is not enabled"
  glance_key:
    value: ''
    label: 'Ceph Key for Glance User'
    description: 'Key that Glance is going to use to access Ceph'
    weight: 25
    type: 'password'
    restrictions:
      - condition: "settings:external-ceph.glance_ceph.value == false"
        message: "External Ceph for Glance images is not enabled"
  glance_pool:
    value: 'images'
    label: 'Ceph Pool Name for Glance'
    description: 'Ceph pool, Glance will be storing images in'
    weight: 30
    type: 'text'
    restrictions:
      - condition: "settings:external-ceph.glance_ceph.value == false"
        message: "External Ceph for Glance images is not enabled"
  cinder_user:
    value: 'cinder'
    label: 'Ceph User for Cinder'
    description: 'Username that Cinder is going to use to access Ceph'
    weight: 35
    type: 'text'
    restrictions:
      - condition: "settings:external-ceph.cinder_ceph.value == false"
        message: "External Ceph for Cinder volumes is not enabled"
  cinder_key:
    value: ''
    label: 'Ceph Key for Cinder'
    description: 'Key that Cinder is going to use to access Ceph'
    weight: 40
    type: 'password'
    restrictions:
      - condition: "settings:external-ceph.cinder_ceph.value == false"
        message: "External Ceph for Cinder volumes is not enabled"
  cinder_pool:
    value: 'volumes'
    label: 'Ceph Pool Name for Cinder'
    description: 'Ceph pool, Cinder will be storing Volumes in'
    weight: 45
    type: 'text'
    restrictions:
      - condition: "settings:external-ceph.cinder_ceph.value == false"
        message: "External Ceph for Cinder volumes is not enabled"
  cinder_backup_user:
    value: 'cinder'
    label: 'Ceph User for Cinder Backups'
    description: 'Username that Cinder is going to use to access Ceph to store volume backups'
    weight: 46
    type: 'text'
    restrictions:
      - condition: "settings:external-ceph.cinder_ceph.value == false"
        message: "External Ceph for Cinder volumes is not enabled"
  cinder_backup_key:
    value: ''
    label: 'Ceph Key for Cinder Backups'
    description: 'Key that Cinder is going to use to access Ceph to store volume backups'
    weight: 47
    type: 'password'
    restrictions:
      - condition: "settings:external-ceph.cinder_ceph.value == false"
        message: "External Ceph for Cinder volumes is not enabled"
  cinder_backup_pool:
    value: 'volumes'
    label: 'Ceph Pool Name for Cinder Backups'
    description: 'Ceph pool, Cinder will be storing volume backups in'
    weight: 48
    type: 'text'
    restrictions:
      - condition: "settings:external-ceph.cinder_ceph.value == false"
        message: "External Ceph for Cinder volumes is not enabled"
  nova_pool:
    value: 'compute'
    label: 'Ceph Pool Name for Nova'
    description: 'Ceph pool, Nova will be storing Ephemeral Drives in'
    weight: 60
    type: 'text'
    restrictions:
      - condition: "settings:external-ceph.nova_ceph.value == false"
        message: "External Ceph for Nova ephemeral drives is not enabled"
